
templateDir: generators/typescript

additionalProperties:
    npmName: '@jmurphyau/example-api-client'
    supportsES6: false
    npmRepository: 'https://npm.pkg.github.com/jmurphyau'

files:
  .github/workflows/actions.yml: {}
