
additionalProperties:
    packageName: ExampleApi.Client
    targetFramework: net7.0
    packageVersion: 1.0.0
    netCoreProjectFile: true
    gitUserId: 'jmurphyau'
    packageAuthors: 'James Murphy'
    packageCompany: 'Example Company'

templateDir: generators/csharp-netcore

files:
  nuget.config: {}
  .github/workflows/actions.yml: {}
