
templateDir: generators/csharp-netcore

additionalProperties:
    packageName: ExampleApi.Client
    targetFramework: net6.0
    netCoreProjectFile: true
    gitUserId: 'jmurphyau'
    gitRepoId: 'ExampleApi.Client'
    packageAuthors: 'James Murphy'
    packageCompany: 'Example Company'

files:
  nuget.config: {}
  .github/workflows/actions.yml: {}
